
  ____  ____   ___    _    ____  _  __     ___  
 |  _ \| __ ) / _ \  / \  |  _ \| |/ /    / _ \ 
 | | | |  _ \| | | |/ _ \ | |_) | ' /____| (_) |
 | |_| | |_) | |_| / ___ \|  __/| . \_____\__, |
 |____/|____/ \___/_/   \_\_|   |_|\_\      /_/ 
                                                
QTH: Koelln-Reisiek - LOC: JO43US  - Sysop: DC6AP 

Mit BBS gelangst Du zur Synchronet BBS
DIR BOARDS zeigt alle vorhandenen Boards an

